# Generated by Django 5.2.3 on 2025-06-26 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="problem",
            name="answer_code",
        ),
    ]
