# Generated by Django 5.2.3 on 2025-06-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_remove_problem_answer_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="userextension",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("admin", "Admin")],
                default="user",
                max_length=10,
            ),
        ),
    ]
