# Generated by Django 5.2.3 on 2025-06-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_userextension_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="examples",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
