# Generated by Django 5.2.3 on 2025-07-03 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_problem_examples"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Submission",
        ),
    ]
