# Generated by Django 5.2.3 on 2025-07-03 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_delete_submission"),
    ]

    operations = [
        migrations.AddField(
            model_name="userextension",
            name="solved_problem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="solved_by_single",
                to="account.problem",
            ),
        ),
    ]
