# Generated by Django 5.2.3 on 2025-07-03 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_userextension_solved_problem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userextension",
            old_name="solved_problem",
            new_name="solved_problems",
        ),
    ]
