# Generated by Django 5.2.3 on 2025-07-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_rename_solved_problem_userextension_solved_problems"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userextension",
            name="solved_problems",
        ),
        migrations.AddField(
            model_name="userextension",
            name="solved_problems",
            field=models.ManyToManyField(
                blank=True, related_name="solved_by_single", to="account.problem"
            ),
        ),
    ]
